services:
  neo4j:
    container_name: neo4j_container
    restart: always
    image: neo4j:3.5.3
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
    volumes:
        - ./neo4j/data:/data
        - ./neo4j/logs:/logs
        - ./neo4j/plugins:/plugins
        - ./neo4j/conf:/conf
    build:
      context: .
      dockerfile: Dockerfile


